### ISSUE TITLE
Other GPIOs?

### ISSUE THREAD

**Issue by koko004** [Howchoo/pi-power-button#18]
Is it possible to use other GPIOs? I already have those pins busy with a HAT 0.96 OLED screen. Thanks for the project it is brilliant and it works perfect.

**Comment by ZLevine** [comment]
Unfortunately, not for 100% functionality. While you can use any other pin for GND, the wake functionality relies on pin 5 (SCL). In order to consume zero power while in the off state, this pin shorting to GND is a sort of "hardware" method of waking the Pi.

So if SCL is in use, you could use an alternate GPIO pin to _shut down_ the Pi, but you wouldn't have wake functionality. If you did this, you'd need to unplug the Pi and plug it back in to turn it on.

Are you 100% sure your screen is _using_ SCL and not just covering it up? [Pinout.xyz](https://pinout.xyz/) is a good resource for identifying which pins are in use.

**Comment by koko004** [comment]
Thanks for your response, bit I think that it´s used
![ezgif com-resize](https://user-images.githubusercontent.com/10567364/84715643-5d515d00-af71-11ea-8f5c-8f5db72cb447.jpg)
![ezgif com-resize (1)](https://user-images.githubusercontent.com/10567364/84715646-5fb3b700-af71-11ea-9380-57077d088ed1.jpg)
